
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scale
  template:
    metadata:
      labels:
        app: scale
    spec:
      containers:
      - name: nginx
        image: nginx

