
apiVersion: v1
kind: Pod
metadata:
  name: downward
  labels:
    app: test
spec:
  containers:
  - name: c
    image: busybox
    command: ["sh","-c","env && sleep 3600"]
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

