
apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  volumes:
  - name: shared
    emptyDir: {}
  containers:
  - name: app
    image: busybox
    command: ["sh","-c","echo hello > /data/file && sleep 3600"]
    volumeMounts:
    - name: shared
      mountPath: /data
  - name: sidecar
    image: busybox
    command: ["sh","-c","tail -f /data/file"]
    volumeMounts:
    - name: shared
      mountPath: /data

