apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: example.yaml
  name: example.yaml
spec:
  replicas: 5
  selector:
    matchLabels:
      app: example.yaml
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: example.yaml
    spec:
      containers:
      - image: nginx:1.25
        name: nginx
        resources: {}
status: {}
